const presidents = [
    { name: "George Washington", party: "Third", elo: 1000 },
    { name: "John Adams", party: "Third", elo: 1000 },
    { name: "Thomas Jefferson", party: "Third", elo: 1000 },
    { name: "James Madison", party: "Third", elo: 1000 },
    { name: "James Monroe", party: "Third", elo: 1000 },
    { name: "John Quincy Adams", party: "Third", elo: 1000 },
    { name: "Andrew Jackson", party: "Democratic", elo: 1000 },
    { name: "Martin Van Buren", party: "Democratic", elo: 1000 },
    { name: "William Henry Harrison", party: "Third", elo: 1000 },
    { name: "John Tyler", party: "Third", elo: 1000 },
    { name: "James K. Polk", party: "Democratic", elo: 1000 },
    { name: "Zachary Taylor", party: "Third", elo: 1000 },
    { name: "Millard Fillmore", party: "Third", elo: 1000 },
    { name: "Franklin Pierce", party: "Democratic", elo: 1000 },
    { name: "James Buchanan", party: "Democratic", elo: 1000 },
    { name: "Abraham Lincoln", party: "Republican", elo: 1000 },
    { name: "Andrew Johnson", party: "Third", elo: 1000 },
    { name: "Ulysses S. Grant", party: "Republican", elo: 1000 },
    { name: "Rutherford B. Hayes", party: "Republican", elo: 1000 },
    { name: "James A. Garfield", party: "Republican", elo: 1000 },
    { name: "Chester A. Arthur", party: "Republican", elo: 1000 },
    { name: "Grover Cleveland", party: "Democratic", elo: 1000 },
    { name: "Benjamin Harrison", party: "Republican", elo: 1000 },
    { name: "William McKinley", party: "Republican", elo: 1000 },
    { name: "Theodore Roosevelt", party: "Republican", elo: 1000 },
    { name: "William Howard Taft", party: "Republican", elo: 1000 },
    { name: "Woodrow Wilson", party: "Democratic", elo: 1000 },
    { name: "Warren G. Harding", party: "Republican", elo: 1000 },
    { name: "Calvin Coolidge", party: "Republican", elo: 1000 },
    { name: "Herbert Hoover", party: "Republican", elo: 1000 },
    { name: "Franklin D. Roosevelt", party: "Democratic", elo: 1000 },
    { name: "Harry S. Truman", party: "Democratic", elo: 1000 },
    { name: "Dwight D. Eisenhower", party: "Republican", elo: 1000 },
    { name: "John F. Kennedy", party: "Democratic", elo: 1000 },
    { name: "Lyndon B. Johnson", party: "Democratic", elo: 1000 },
    { name: "Richard Nixon", party: "Republican", elo: 1000 },
    { name: "Gerald Ford", party: "Republican", elo: 1000 },
    { name: "Jimmy Carter", party: "Democratic", elo: 1000 },
    { name: "Ronald Reagan", party: "Republican", elo: 1000 },
    { name: "George H. W. Bush", party: "Republican", elo: 1000 },
    { name: "Bill Clinton", party: "Democratic", elo: 1000 },
    { name: "George W. Bush", party: "Republican", elo: 1000 },
    { name: "Barack Obama", party: "Democratic", elo: 1000 },
    { name: "Donald Trump", party: "Republican", elo: 1000 },
    { name: "Joe Biden", party: "Democratic", elo: 1000 }
]

export default presidents;
