let packsArr = JSON.parse(localStorage.getItem('packs'))
if (packsArr == null) {
    let presidents = [
        { name: "George Washington", attribute: "Third", elo: 1000 },
        { name: "John Adams", attribute: "Third", elo: 1000 },
        { name: "Thomas Jefferson", attribute: "Third", elo: 1000 },
        { name: "James Madison", attribute: "Third", elo: 1000 },
        { name: "James Monroe", attribute: "Third", elo: 1000 },
        { name: "John Quincy Adams", attribute: "Third", elo: 1000 },
        { name: "Andrew Jackson", attribute: "Democratic", elo: 1000 },
        { name: "Martin Van Buren", attribute: "Democratic", elo: 1000 },
        { name: "William Henry Harrison", attribute: "Third", elo: 1000 },
        { name: "John Tyler", attribute: "Third", elo: 1000 },
        { name: "James K. Polk", attribute: "Democratic", elo: 1000 },
        { name: "Zachary Taylor", attribute: "Third", elo: 1000 },
        { name: "Millard Fillmore", attribute: "Third", elo: 1000 },
        { name: "Franklin Pierce", attribute: "Democratic", elo: 1000 },
        { name: "James Buchanan", attribute: "Democratic", elo: 1000 },
        { name: "Abraham Lincoln", attribute: "Republican", elo: 1000 },
        { name: "Andrew Johnson", attribute: "Third", elo: 1000 },
        { name: "Ulysses S. Grant", attribute: "Republican", elo: 1000 },
        { name: "Rutherford B. Hayes", attribute: "Republican", elo: 1000 },
        { name: "James A. Garfield", attribute: "Republican", elo: 1000 },
        { name: "Chester A. Arthur", attribute: "Republican", elo: 1000 },
        { name: "Grover Cleveland", attribute: "Democratic", elo: 1000 },
        { name: "Benjamin Harrison", attribute: "Republican", elo: 1000 },
        { name: "William McKinley", attribute: "Republican", elo: 1000 },
        { name: "Theodore Roosevelt", attribute: "Republican", elo: 1000 },
        { name: "William Howard Taft", attribute: "Republican", elo: 1000 },
        { name: "Woodrow Wilson", attribute: "Democratic", elo: 1000 },
        { name: "Warren G. Harding", attribute: "Republican", elo: 1000 },
        { name: "Calvin Coolidge", attribute: "Republican", elo: 1000 },
        { name: "Herbert Hoover", attribute: "Republican", elo: 1000 },
        { name: "Franklin D. Roosevelt", attribute: "Democratic", elo: 1000 },
        { name: "Harry S. Truman", attribute: "Democratic", elo: 1000 },
        { name: "Dwight D. Eisenhower", attribute: "Republican", elo: 1000 },
        { name: "John F. Kennedy", attribute: "Democratic", elo: 1000 },
        { name: "Lyndon B. Johnson", attribute: "Democratic", elo: 1000 },
        { name: "Richard Nixon", attribute: "Republican", elo: 1000 },
        { name: "Gerald Ford", attribute: "Republican", elo: 1000 },
        { name: "Jimmy Carter", attribute: "Democratic", elo: 1000 },
        { name: "Ronald Reagan", attribute: "Republican", elo: 1000 },
        { name: "George H. W. Bush", attribute: "Republican", elo: 1000 },
        { name: "Bill Clinton", attribute: "Democratic", elo: 1000 },
        { name: "George W. Bush", attribute: "Republican", elo: 1000 },
        { name: "Barack Obama", attribute: "Democratic", elo: 1000 },
        { name: "Donald Trump", attribute: "Republican", elo: 1000 },
        { name: "Joe Biden", attribute: "Democratic", elo: 1000 }
    ]
    let colors = [
        { name: "Red", attribute: "Warm", elo: 1000 },
        { name: "Black", attribute: "Other", elo: 1000 },
        { name: "Blue", attribute: "Cool", elo: 1000 },
        { name: "Green", attribute: "Cool", elo: 1000 },
        { name: "Yellow", attribute: "Warm", elo: 1000 },
        { name: "Orange", attribute: "Warm", elo: 1000 },
        { name: "Purple", attribute: "Cool", elo: 1000 },
        { name: "Pink", attribute: "Warm", elo: 1000 },
        { name: "Brown", attribute: "Other", elo: 1000 },
        { name: "Gray", attribute: "Other", elo: 1000 },
        { name: "White", attribute: "Other", elo: 1000 },
        { name: "Cyan", attribute: "Cool", elo: 1000 },
        { name: "Magenta", attribute: "Warm", elo: 1000 },
        { name: "Teal", attribute: "Cool", elo: 1000 },
        { name: "Lavender", attribute: "Cool", elo: 1000 },
        { name: "Gold", attribute: "Warm", elo: 1000 },
        { name: "Silver", attribute: "Other", elo: 1000 },
    ]
    let packInfo = ["Presidents", "Colors"]
    packsArr = [packInfo, presidents, colors]
}


export default packsArr;
